[package]
name = "aoc2020"
description = "My solutions for https://adventofcode.com"
version = "0.1.0"
authors = ["Ludwig Stecher <ludwig.stecher@gmx.de>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
regex = "1"
